version: '3.8'

services:
  app:
    build: .
    container_name: crane_bot_app
    restart: always
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    volumes:
      - ./:/app

  db:
    image: postgres:15
    container_name: crane_bot_db
    restart: always
    environment:
      POSTGRES_DB: fixed_crane_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: acfy0ver
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
